INSERT INTO EVENT (ID, NAME, START_DATETIME, LOCATION, DESCRIPTION)
VALUES (5, 'Event Name 5', CURRENT_TIMESTAMP, 'Tallinn', 'Description 5');

INSERT INTO PAYMENT_TYPE (ID, TYPE_VALUE)
VALUES (5, 'Kiirmakse');

INSERT INTO LEGAL_ENTITY (ID, NAME, REGISTRATION_CODE)
VALUES (5, 'IT Solutions OÜ', '77777777');

INSERT INTO EVENT_LEGAL_ENTITY_PARTICIPANT (ID, EVENT_ID, LEGAL_ENTITY_ID, PAYMENT_TYPE_ID, PARTICIPANT_COUNT)
VALUES (5, 5, 5, 5, 1);