INSERT INTO EVENT (ID, NAME, START_DATETIME, LOCATION, DESCRIPTION)
VALUES (9, 'Event Name 9', CURRENT_TIMESTAMP, 'Tallinn', 'Description 9');

INSERT INTO PAYMENT_TYPE (ID, TYPE_VALUE)
VALUES (1, 'Pangaülekanne');

INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, NATIONAL_IDENTIFICATION_CODE)
VALUES (9, 'Janar', 'Rahumeel', '38008180024');

INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, NATIONAL_IDENTIFICATION_CODE)
VALUES (10, 'Janar', 'Tasane', '38008180026');

INSERT INTO LEGAL_ENTITY (ID, NAME, REGISTRATION_CODE)
VALUES (9, 'Janar Solutions OÜ', '88888888');

INSERT INTO EVENT_PERSON_PARTICIPANT (ID, EVENT_ID, PERSON_ID, PAYMENT_TYPE_ID)
VALUES (9, 9, 9, 1);

INSERT INTO EVENT_PERSON_PARTICIPANT (ID, EVENT_ID, PERSON_ID, PAYMENT_TYPE_ID)
VALUES (10, 9, 10, SELECT ID FROM PAYMENT_TYPE WHERE TYPE_VALUE = 'Sularaha');

INSERT INTO EVENT_LEGAL_ENTITY_PARTICIPANT (ID, EVENT_ID, LEGAL_ENTITY_ID, PARTICIPANT_COUNT, PAYMENT_TYPE_ID)
VALUES (9, 9, 9, 1, SELECT ID FROM PAYMENT_TYPE WHERE TYPE_VALUE = 'Ülekanne');