INSERT INTO EVENT (ID, NAME, START_DATETIME, LOCATION, DESCRIPTION)
VALUES (3, 'Event Name 3', CURRENT_TIMESTAMP, 'Tallinn', 'Description 3');

INSERT INTO PAYMENT_TYPE (ID, TYPE_VALUE)
VALUES (3, 'Krüpto');

INSERT INTO PERSON_PARTICIPANT (ID, FIRST_NAME, LAST_NAME, NATIONAL_IDENTIFICATION_CODE, PAYMENT_TYPE_ID)
VALUES (3, 'Janar', 'Rahumeel', '61905270055', 3);

INSERT INTO EVENT_PERSON_PARTICIPANT_X (EVENT_ID, PERSON_PARTICIPANT_ID)
VALUES (3, 3);