INSERT INTO EVENT (ID, NAME, START_DATETIME, LOCATION, DESCRIPTION)
VALUES (6, 'Event Name 6', CURRENT_TIMESTAMP, 'Tallinn', 'Description 6');

INSERT INTO PAYMENT_TYPE (ID, TYPE_VALUE)
VALUES (6, 'Välkmakse');