INSERT INTO EVENT (ID, NAME, START_DATETIME, LOCATION, DESCRIPTION)
VALUES (2, 'Event Name 2', CURRENT_TIMESTAMP, 'Tallinn', 'Description 2');

INSERT INTO PAYMENT_TYPE (ID, TYPE_VALUE)
VALUES (1, 'Pangaülekanne');

INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, NATIONAL_IDENTIFICATION_CODE)
VALUES (1, 'Janar', 'Rahumeel', '38008180024');

INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, NATIONAL_IDENTIFICATION_CODE)
VALUES (2, 'Janar', 'Tasane', '38008180026');

INSERT INTO LEGAL_ENTITY_PARTICIPANT (ID, NAME, REGISTRATION_CODE, PARTICIPANT_COUNT, PAYMENT_TYPE_ID)
VALUES (1, 'Janar Solutions OÜ', '88888888', 1, SELECT ID FROM PAYMENT_TYPE WHERE TYPE_VALUE = 'Sularaha');

INSERT INTO EVENT_PERSON_PARTICIPANT (ID, EVENT_ID, PERSON_ID, PAYMENT_TYPE_ID)
VALUES (2, 2, 1, 1);

INSERT INTO EVENT_PERSON_PARTICIPANT (ID, EVENT_ID, PERSON_ID, PAYMENT_TYPE_ID)
VALUES (3, 2, 2, SELECT ID FROM PAYMENT_TYPE WHERE TYPE_VALUE = 'Sularaha');

INSERT INTO EVENT_LEGAL_ENTITY_PARTICIPANT_X (EVENT_ID, LEGAL_ENTITY_PARTICIPANT_ID)
VALUES (2, 1);