INSERT INTO EVENT (ID, NAME, START_DATETIME, LOCATION, DESCRIPTION)
VALUES (4, 'Event Name 4', CURRENT_TIMESTAMP, 'Tallinn', 'Description 4');

INSERT INTO PAYMENT_TYPE (ID, TYPE_VALUE)
VALUES (4, 'SEPA Makse');