CREATE USER rik WITH ENCRYPTED PASSWORD 'changeme';
GRANT ALL ON SCHEMA public TO rik;

CREATE DATABASE rik_test;
GRANT ALL PRIVILEGES ON DATABASE rik_test TO rik;
ALTER DATABASE rik_test OWNER TO rik;